// Rich detail data for each tournament (frontend mock only)
import type { TournamentDetail } from "@/features/tournaments/types";
import { buildDoubleElimBracket, buildSingleElimBracket } from "@/lib/mock-brackets";

// ── Shared rule sections reused across tournaments ─────────────────────────

const standardRules: import("@/features/tournaments/types").RuleSection[] = [
  {
    title: "Eligibility",
    items: [
      "All players must be registered Black Rose members.",
      "Each team must have a minimum of 5 players and a maximum of 7 (including substitutes).",
      "Players may not compete for more than one team in the same tournament.",
      "Age requirement: 16 years or older.",
    ],
  },
  {
    title: "Match Conduct",
    items: [
      "Teams must be present in the designated lobby 10 minutes before match time.",
      "A no-show after 15 minutes from the scheduled start results in a forfeit.",
      "Use of cheats, exploits, or unauthorized software results in immediate disqualification.",
      "Respectful conduct toward opponents, staff, and spectators is mandatory.",
    ],
  },
  {
    title: "Substitutions",
    items: [
      "Substitutions may be made between maps, not mid-map.",
      "Substitutes must be on the registered roster before the tournament starts.",
    ],
  },
  {
    title: "Disputes",
    items: [
      "All disputes must be submitted to staff within 10 minutes of the match ending.",
      "Staff decisions are final.",
      "Screenshot or video evidence is required for any disputed call.",
    ],
  },
];

// ── Tournament detail records ──────────────────────────────────────────────

export const mockTournamentDetails: Record<string, TournamentDetail> = {
  "vlr-nightfall": {
    id: "vlr-nightfall",
    name: "Valorant Nightfall Cup",
    game: "Valorant",
    status: "Registration Open",
    prizePool: "₱10,000",
    startDate: "2026-06-21",
    registrationDeadline: "2026-06-18",
    teamsRegistered: 16,
    teamCap: 32,
    format: "Single Elimination",
    region: "PH",
    description:
      "The Nightfall Cup is Black Rose's flagship Valorant invitational — a grueling single-elimination battle across two weekends to crown the best squad in the Philippines. Bring your sharpest roster and prove you belong at the top.",
    organizer: "Black Rose Operations",
    contact: "ops@blackrose.gg",
    prizeBreakdown: [
      { place: "1st Place", prize: "₱5,000" },
      { place: "2nd Place", prize: "₱2,500" },
      { place: "3rd–4th Place", prize: "₱1,250 each" },
    ],
    schedule: [
      { phase: "Registration Closes", date: "2026-06-18" },
      { phase: "Round of 16", date: "2026-06-21", note: "16 teams enter" },
      { phase: "Quarterfinals", date: "2026-06-22", note: "Top 8 advance" },
      { phase: "Semifinals", date: "2026-06-27" },
      { phase: "Grand Finals", date: "2026-06-29", note: "Best of 3" },
    ],
    rules: standardRules,
    teams: [
      {
        id: "t-001",
        name: "Novellino eSports",
        tag: "NE",
        captain: "CoyHa",
        seed: 1,
        players: [
          { ign: "CoyHa", role: "Duelist / IGL" },
          { ign: "Chewie", role: "Controller" },
          { ign: "Cent", role: "Initiator" },
          { ign: "Kiraz", role: "Sentinel" },
          { ign: "Ashburn", role: "Flex" },
        ],
      },
      {
        id: "t-002",
        name: "Crimson Halo",
        tag: "CRH",
        captain: "halox",
        seed: 2,
        players: [
          { ign: "halox", role: "IGL" },
          { ign: "sable", role: "Duelist" },
          { ign: "nyx", role: "Controller" },
          { ign: "iris", role: "Initiator" },
          { ign: "drev", role: "Sentinel" },
        ],
      },
      {
        id: "t-004",
        name: "Phoenix Rising",
        tag: "PHX",
        captain: "saira",
        seed: 3,
        players: [
          { ign: "saira", role: "Duelist" },
          { ign: "kaen", role: "Controller" },
          { ign: "vex", role: "Initiator" },
          { ign: "lior", role: "Sentinel" },
          { ign: "noor", role: "Flex" },
        ],
      },
      {
        id: "t-005",
        name: "Ash Reapers",
        tag: "ASH",
        captain: "rave",
        seed: 4,
        players: [
          { ign: "rave", role: "IGL" },
          { ign: "byte", role: "Duelist" },
          { ign: "nova", role: "Sentinel" },
          { ign: "Quamico", role: "Initiator" },
          { ign: "ire", role: "Controller" },
        ],
      },
      {
        id: "t-006",
        name: "Viper Squad",
        tag: "VPR",
        captain: "toxin",
        seed: 5,
        players: [
          { ign: "toxin", role: "Controller / IGL" },
          { ign: "venom", role: "Duelist" },
          { ign: "spike", role: "Initiator" },
          { ign: "steel", role: "Sentinel" },
          { ign: "flash", role: "Flex" },
        ],
      },
      {
        id: "t-007",
        name: "Thunder Wolves",
        tag: "TWF",
        captain: "storm",
        seed: 6,
        players: [
          { ign: "storm", role: "Duelist" },
          { ign: "lightning", role: "IGL" },
          { ign: "thunder", role: "Controller" },
          { ign: "bolt", role: "Initiator" },
          { ign: "spark", role: "Sentinel" },
        ],
      },
      {
        id: "t-008",
        name: "Neon Guardians",
        tag: "NGU",
        captain: "cyber",
        seed: 7,
        players: [
          { ign: "cyber", role: "Controller / IGL" },
          { ign: "neon", role: "Duelist" },
          { ign: "pixel", role: "Initiator" },
          { ign: "matrix", role: "Sentinel" },
          { ign: "glitch", role: "Flex" },
        ],
      },
      {
        id: "t-009",
        name: "Mystic Shadows",
        tag: "MSH",
        captain: "shadow",
        seed: 8,
        players: [
          { ign: "shadow", role: "Duelist" },
          { ign: "phantom", role: "Controller" },
          { ign: "wraith", role: "IGL" },
          { ign: "shade", role: "Initiator" },
          { ign: "void", role: "Sentinel" },
        ],
      },
      {
        id: "t-010",
        name: "Apex Predators",
        tag: "APX",
        captain: "hunter",
        seed: 9,
        players: [
          { ign: "hunter", role: "IGL" },
          { ign: "predator", role: "Duelist" },
          { ign: "stalker", role: "Initiator" },
          { ign: "prowler", role: "Controller" },
          { ign: "beast", role: "Sentinel" },
        ],
      },
      {
        id: "t-011",
        name: "Iron Titans",
        tag: "ITN",
        captain: "titan",
        seed: 10,
        players: [
          { ign: "titan", role: "Sentinel / IGL" },
          { ign: "forge", role: "Duelist" },
          { ign: "anvil", role: "Controller" },
          { ign: "hammer", role: "Initiator" },
          { ign: "steel", role: "Flex" },
        ],
      },
      {
        id: "t-012",
        name: "Frost Legion",
        tag: "FLG",
        captain: "frost",
        seed: 11,
        players: [
          { ign: "frost", role: "Controller / IGL" },
          { ign: "ice", role: "Duelist" },
          { ign: "blizzard", role: "Initiator" },
          { ign: "arctic", role: "Sentinel" },
          { ign: "glacier", role: "Flex" },
        ],
      },
      {
        id: "t-013",
        name: "Solar Flare",
        tag: "SOL",
        captain: "solar",
        seed: 12,
        players: [
          { ign: "solar", role: "Duelist" },
          { ign: "flare", role: "IGL" },
          { ign: "burn", role: "Controller" },
          { ign: "ember", role: "Initiator" },
          { ign: "flame", role: "Sentinel" },
        ],
      },
      {
        id: "t-014",
        name: "Quantum Strike",
        tag: "QTS",
        captain: "quantum",
        seed: 13,
        players: [
          { ign: "quantum", role: "Controller / IGL" },
          { ign: "particle", role: "Duelist" },
          { ign: "atom", role: "Initiator" },
          { ign: "photon", role: "Sentinel" },
          { ign: "neuron", role: "Flex" },
        ],
      },
      {
        id: "t-015",
        name: "Void Walkers",
        tag: "VWK",
        captain: "void",
        seed: 14,
        players: [
          { ign: "void", role: "Duelist" },
          { ign: "walker", role: "IGL" },
          { ign: "dimension", role: "Controller" },
          { ign: "portal", role: "Initiator" },
          { ign: "rift", role: "Sentinel" },
        ],
      },
      {
        id: "t-016",
        name: "Eclipse Warriors",
        tag: "ECW",
        captain: "eclipse",
        seed: 15,
        players: [
          { ign: "eclipse", role: "Controller / IGL" },
          { ign: "warrior", role: "Duelist" },
          { ign: "moon", role: "Initiator" },
          { ign: "sun", role: "Sentinel" },
          { ign: "star", role: "Flex" },
        ],
      },
      {
        id: "t-017",
        name: "Raven Strike",
        tag: "RST",
        captain: "raven",
        seed: 16,
        players: [
          { ign: "raven", role: "Duelist / IGL" },
          { ign: "strike", role: "Controller" },
          { ign: "shadow", role: "Initiator" },
          { ign: "blade", role: "Sentinel" },
          { ign: "storm", role: "Flex" },
        ],
      },
    ],
    bracket: buildSingleElimBracket([
      "Novellino eSports",
      "Crimson Halo",
      "Phoenix Rising",
      "Ash Reapers",
      "Viper Squad",
      "Thunder Wolves",
      "Neon Guardians",
      "Mystic Shadows",
      "Apex Predators",
      "Iron Titans",
      "Frost Legion",
      "Solar Flare",
      "Quantum Strike",
      "Void Walkers",
      "Eclipse Warriors",
      "Raven Strike",
    ]),
  },
  "lol-twilight": {
    id: "lol-twilight",
    name: "Twilight Clash",
    game: "League of Legends",
    status: "Registration Closed",
    prizePool: "$5,000",
    startDate: "2026-07-12",
    registrationDeadline: "2026-07-08",
    teamsRegistered: 8,
    teamCap: 16,
    format: "Double Elimination",
    region: "SEA",
    description:
      "Twilight Clash is Black Rose's 8-team League of Legends double-elimination event — upper and lower brackets feed into a grand final showdown.",
    organizer: "Black Rose Operations",
    contact: "ops@blackrose.gg",
    prizeBreakdown: [
      { place: "1st Place", prize: "$2,500" },
      { place: "2nd Place", prize: "$1,250" },
      { place: "3rd Place", prize: "$750" },
      { place: "4th Place", prize: "$500" },
    ],
    schedule: [
      { phase: "Registration Closes", date: "2026-07-08" },
      { phase: "Upper Bracket — Round 1", date: "2026-07-12", note: "8 teams" },
      { phase: "Lower Bracket — Opening", date: "2026-07-13", note: "First-round losers drop" },
      { phase: "Upper & Lower Finals", date: "2026-07-19" },
      { phase: "Grand Final", date: "2026-07-20", note: "Bracket reset if needed" },
    ],
    rules: standardRules,
    teams: [
      {
        id: "t-tw-001",
        name: "Neon Syndicate",
        tag: "NSY",
        captain: "pulse",
        seed: 1,
        players: [
          { ign: "pulse", role: "Top" },
          { ign: "wire", role: "Jungle" },
          { ign: "flux", role: "Mid" },
          { ign: "grid", role: "ADC" },
          { ign: "arc", role: "Support" },
        ],
      },
      {
        id: "t-tw-002",
        name: "Obsidian Core",
        tag: "OBS",
        captain: "onyx",
        seed: 2,
        players: [
          { ign: "onyx", role: "Top" },
          { ign: "shard", role: "Jungle" },
          { ign: "basalt", role: "Mid" },
          { ign: "flint", role: "ADC" },
          { ign: "slate", role: "Support" },
        ],
      },
      {
        id: "t-tw-003",
        name: "Pulse Breakers",
        tag: "PLS",
        captain: "beat",
        seed: 3,
        players: [
          { ign: "beat", role: "Top" },
          { ign: "tempo", role: "Jungle" },
          { ign: "echo", role: "Mid" },
          { ign: "rhythm", role: "ADC" },
          { ign: "bass", role: "Support" },
        ],
      },
      {
        id: "t-tw-004",
        name: "Cipher Unit",
        tag: "CPH",
        captain: "key",
        seed: 4,
        players: [
          { ign: "key", role: "Top" },
          { ign: "lock", role: "Jungle" },
          { ign: "hash", role: "Mid" },
          { ign: "token", role: "ADC" },
          { ign: "byte", role: "Support" },
        ],
      },
      {
        id: "t-tw-005",
        name: "Aurora Five",
        tag: "AUR",
        captain: "dawn",
        seed: 5,
        players: [
          { ign: "dawn", role: "Top" },
          { ign: "glow", role: "Jungle" },
          { ign: "ray", role: "Mid" },
          { ign: "halo", role: "ADC" },
          { ign: "lumen", role: "Support" },
        ],
      },
      {
        id: "t-tw-006",
        name: "Static Reign",
        tag: "STC",
        captain: "volt",
        seed: 6,
        players: [
          { ign: "volt", role: "Top" },
          { ign: "surge", role: "Jungle" },
          { ign: "ohm", role: "Mid" },
          { ign: "amp", role: "ADC" },
          { ign: "watt", role: "Support" },
        ],
      },
      {
        id: "t-tw-007",
        name: "Midnight Forge",
        tag: "MFG",
        captain: "anvil",
        seed: 7,
        players: [
          { ign: "anvil", role: "Top" },
          { ign: "ember", role: "Jungle" },
          { ign: "coal", role: "Mid" },
          { ign: "spark", role: "ADC" },
          { ign: "iron", role: "Support" },
        ],
      },
      {
        id: "t-tw-008",
        name: "Zenith Line",
        tag: "ZEN",
        captain: "apex",
        seed: 8,
        players: [
          { ign: "apex", role: "Top" },
          { ign: "peak", role: "Jungle" },
          { ign: "ridge", role: "Mid" },
          { ign: "crest", role: "ADC" },
          { ign: "summit", role: "Support" },
        ],
      },
    ],
    bracket: buildDoubleElimBracket([
      "Neon Syndicate",
      "Obsidian Core",
      "Pulse Breakers",
      "Cipher Unit",
      "Aurora Five",
      "Static Reign",
      "Midnight Forge",
      "Zenith Line",
    ]),
  },
};
