/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TournamentsIdRouteImport } from './routes/tournaments.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTournamentsRouteImport } from './routes/admin.tournaments'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminParticipantsRouteImport } from './routes/admin.participants'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminTournamentsIdRouteImport } from './routes/admin.tournaments.$id'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TournamentsRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TournamentsIdRoute = TournamentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TournamentsRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTournamentsRoute = AdminTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTournamentsIdRoute = AdminTournamentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTournamentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/waitlist': typeof WaitlistRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/tournaments': typeof AdminTournamentsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/waitlist': typeof WaitlistRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/tournaments': typeof AdminTournamentsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/admin': typeof AdminIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tournaments': typeof TournamentsRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/waitlist': typeof WaitlistRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/tournaments': typeof AdminTournamentsRouteWithChildren
  '/admin/users': typeof AdminUsersRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/tournaments'
    | '/unauthorized'
    | '/waitlist'
    | '/admin/announcements'
    | '/admin/participants'
    | '/admin/settings'
    | '/admin/teams'
    | '/admin/tournaments'
    | '/admin/users'
    | '/tournaments/$id'
    | '/admin/'
    | '/tournaments/'
    | '/admin/tournaments/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/waitlist'
    | '/admin/announcements'
    | '/admin/participants'
    | '/admin/settings'
    | '/admin/teams'
    | '/admin/tournaments'
    | '/admin/users'
    | '/tournaments/$id'
    | '/admin'
    | '/tournaments'
    | '/admin/tournaments/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/register'
    | '/tournaments'
    | '/unauthorized'
    | '/waitlist'
    | '/admin/announcements'
    | '/admin/participants'
    | '/admin/settings'
    | '/admin/teams'
    | '/admin/tournaments'
    | '/admin/users'
    | '/tournaments/$id'
    | '/admin/'
    | '/tournaments/'
    | '/admin/tournaments/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TournamentsRoute: typeof TournamentsRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  WaitlistRoute: typeof WaitlistRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tournaments/$id': {
      id: '/tournaments/$id'
      path: '/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tournaments': {
      id: '/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AdminTournamentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tournaments/$id': {
      id: '/admin/tournaments/$id'
      path: '/$id'
      fullPath: '/admin/tournaments/$id'
      preLoaderRoute: typeof AdminTournamentsIdRouteImport
      parentRoute: typeof AdminTournamentsRoute
    }
  }
}

interface AdminTournamentsRouteChildren {
  AdminTournamentsIdRoute: typeof AdminTournamentsIdRoute
}

const AdminTournamentsRouteChildren: AdminTournamentsRouteChildren = {
  AdminTournamentsIdRoute: AdminTournamentsIdRoute,
}

const AdminTournamentsRouteWithChildren =
  AdminTournamentsRoute._addFileChildren(AdminTournamentsRouteChildren)

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminTournamentsRoute: typeof AdminTournamentsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminTournamentsRoute: AdminTournamentsRouteWithChildren,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface TournamentsRouteChildren {
  TournamentsIdRoute: typeof TournamentsIdRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
}

const TournamentsRouteChildren: TournamentsRouteChildren = {
  TournamentsIdRoute: TournamentsIdRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
}

const TournamentsRouteWithChildren = TournamentsRoute._addFileChildren(
  TournamentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TournamentsRoute: TournamentsRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  WaitlistRoute: WaitlistRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
