/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaitlistRouteImport } from './routes/waitlist'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as TournamentsRouteImport } from './routes/tournaments'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TournamentsIndexRouteImport } from './routes/tournaments.index'
import { Route as TeamsIndexRouteImport } from './routes/teams.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as CommunityIndexRouteImport } from './routes/community.index'
import { Route as ChampionsIndexRouteImport } from './routes/champions.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TournamentsIdRouteImport } from './routes/tournaments.$id'
import { Route as TeamsCreateRouteImport } from './routes/teams.create'
import { Route as TeamsIdRouteImport } from './routes/teams.$id'
import { Route as MembersSlugRouteImport } from './routes/members.$slug'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminTournamentsRouteImport } from './routes/admin.tournaments'
import { Route as AdminTeamsRouteImport } from './routes/admin.teams'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminParticipantsRouteImport } from './routes/admin.participants'
import { Route as AdminAuditLogRouteImport } from './routes/admin.audit-log'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin.announcements'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminTournamentsIndexRouteImport } from './routes/admin.tournaments.index'
import { Route as AdminUsersMemberIdRouteImport } from './routes/admin.users.$memberId'
import { Route as AdminTournamentsIdRouteImport } from './routes/admin.tournaments.$id'

const WaitlistRoute = WaitlistRouteImport.update({
  id: '/waitlist',
  path: '/waitlist',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsRoute = TournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TournamentsIndexRoute = TournamentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TournamentsRoute,
} as any)
const TeamsIndexRoute = TeamsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeamsRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const CommunityIndexRoute = CommunityIndexRouteImport.update({
  id: '/community/',
  path: '/community/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChampionsIndexRoute = ChampionsIndexRouteImport.update({
  id: '/champions/',
  path: '/champions/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TournamentsIdRoute = TournamentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TournamentsRoute,
} as any)
const TeamsCreateRoute = TeamsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => TeamsRoute,
} as any)
const TeamsIdRoute = TeamsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TeamsRoute,
} as any)
const MembersSlugRoute = MembersSlugRouteImport.update({
  id: '/members/$slug',
  path: '/members/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTournamentsRoute = AdminTournamentsRouteImport.update({
  id: '/tournaments',
  path: '/tournaments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamsRoute = AdminTeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParticipantsRoute = AdminParticipantsRouteImport.update({
  id: '/participants',
  path: '/participants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminTournamentsIndexRoute = AdminTournamentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTournamentsRoute,
} as any)
const AdminUsersMemberIdRoute = AdminUsersMemberIdRouteImport.update({
  id: '/$memberId',
  path: '/$memberId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminTournamentsIdRoute = AdminTournamentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminTournamentsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/teams': typeof TeamsRouteWithChildren
  '/tournaments': typeof TournamentsRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/waitlist': typeof WaitlistRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/tournaments': typeof AdminTournamentsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/members/$slug': typeof MembersSlugRoute
  '/teams/$id': typeof TeamsIdRoute
  '/teams/create': typeof TeamsCreateRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/champions/': typeof ChampionsIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
  '/admin/users/$memberId': typeof AdminUsersMemberIdRoute
  '/admin/tournaments/': typeof AdminTournamentsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/waitlist': typeof WaitlistRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/members/$slug': typeof MembersSlugRoute
  '/teams/$id': typeof TeamsIdRoute
  '/teams/create': typeof TeamsCreateRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/admin': typeof AdminIndexRoute
  '/champions': typeof ChampionsIndexRoute
  '/community': typeof CommunityIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/teams': typeof TeamsIndexRoute
  '/tournaments': typeof TournamentsIndexRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
  '/admin/users/$memberId': typeof AdminUsersMemberIdRoute
  '/admin/tournaments': typeof AdminTournamentsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/teams': typeof TeamsRouteWithChildren
  '/tournaments': typeof TournamentsRouteWithChildren
  '/unauthorized': typeof UnauthorizedRoute
  '/waitlist': typeof WaitlistRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/audit-log': typeof AdminAuditLogRoute
  '/admin/participants': typeof AdminParticipantsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/teams': typeof AdminTeamsRoute
  '/admin/tournaments': typeof AdminTournamentsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/members/$slug': typeof MembersSlugRoute
  '/teams/$id': typeof TeamsIdRoute
  '/teams/create': typeof TeamsCreateRoute
  '/tournaments/$id': typeof TournamentsIdRoute
  '/admin/': typeof AdminIndexRoute
  '/champions/': typeof ChampionsIndexRoute
  '/community/': typeof CommunityIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/teams/': typeof TeamsIndexRoute
  '/tournaments/': typeof TournamentsIndexRoute
  '/admin/tournaments/$id': typeof AdminTournamentsIdRoute
  '/admin/users/$memberId': typeof AdminUsersMemberIdRoute
  '/admin/tournaments/': typeof AdminTournamentsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/teams'
    | '/tournaments'
    | '/unauthorized'
    | '/waitlist'
    | '/admin/announcements'
    | '/admin/audit-log'
    | '/admin/participants'
    | '/admin/settings'
    | '/admin/teams'
    | '/admin/tournaments'
    | '/admin/users'
    | '/auth/callback'
    | '/dashboard/profile'
    | '/members/$slug'
    | '/teams/$id'
    | '/teams/create'
    | '/tournaments/$id'
    | '/admin/'
    | '/champions/'
    | '/community/'
    | '/dashboard/'
    | '/teams/'
    | '/tournaments/'
    | '/admin/tournaments/$id'
    | '/admin/users/$memberId'
    | '/admin/tournaments/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/unauthorized'
    | '/waitlist'
    | '/admin/announcements'
    | '/admin/audit-log'
    | '/admin/participants'
    | '/admin/settings'
    | '/admin/teams'
    | '/auth/callback'
    | '/dashboard/profile'
    | '/members/$slug'
    | '/teams/$id'
    | '/teams/create'
    | '/tournaments/$id'
    | '/admin'
    | '/champions'
    | '/community'
    | '/dashboard'
    | '/teams'
    | '/tournaments'
    | '/admin/tournaments/$id'
    | '/admin/users/$memberId'
    | '/admin/tournaments'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/teams'
    | '/tournaments'
    | '/unauthorized'
    | '/waitlist'
    | '/admin/announcements'
    | '/admin/audit-log'
    | '/admin/participants'
    | '/admin/settings'
    | '/admin/teams'
    | '/admin/tournaments'
    | '/admin/users'
    | '/auth/callback'
    | '/dashboard/profile'
    | '/members/$slug'
    | '/teams/$id'
    | '/teams/create'
    | '/tournaments/$id'
    | '/admin/'
    | '/champions/'
    | '/community/'
    | '/dashboard/'
    | '/teams/'
    | '/tournaments/'
    | '/admin/tournaments/$id'
    | '/admin/users/$memberId'
    | '/admin/tournaments/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TeamsRoute: typeof TeamsRouteWithChildren
  TournamentsRoute: typeof TournamentsRouteWithChildren
  UnauthorizedRoute: typeof UnauthorizedRoute
  WaitlistRoute: typeof WaitlistRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  MembersSlugRoute: typeof MembersSlugRoute
  ChampionsIndexRoute: typeof ChampionsIndexRoute
  CommunityIndexRoute: typeof CommunityIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waitlist': {
      id: '/waitlist'
      path: '/waitlist'
      fullPath: '/waitlist'
      preLoaderRoute: typeof WaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments': {
      id: '/tournaments'
      path: '/tournaments'
      fullPath: '/tournaments'
      preLoaderRoute: typeof TournamentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tournaments/': {
      id: '/tournaments/'
      path: '/'
      fullPath: '/tournaments/'
      preLoaderRoute: typeof TournamentsIndexRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/teams/': {
      id: '/teams/'
      path: '/'
      fullPath: '/teams/'
      preLoaderRoute: typeof TeamsIndexRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/community/': {
      id: '/community/'
      path: '/community'
      fullPath: '/community/'
      preLoaderRoute: typeof CommunityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/champions/': {
      id: '/champions/'
      path: '/champions'
      fullPath: '/champions/'
      preLoaderRoute: typeof ChampionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/tournaments/$id': {
      id: '/tournaments/$id'
      path: '/$id'
      fullPath: '/tournaments/$id'
      preLoaderRoute: typeof TournamentsIdRouteImport
      parentRoute: typeof TournamentsRoute
    }
    '/teams/create': {
      id: '/teams/create'
      path: '/create'
      fullPath: '/teams/create'
      preLoaderRoute: typeof TeamsCreateRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/teams/$id': {
      id: '/teams/$id'
      path: '/$id'
      fullPath: '/teams/$id'
      preLoaderRoute: typeof TeamsIdRouteImport
      parentRoute: typeof TeamsRoute
    }
    '/members/$slug': {
      id: '/members/$slug'
      path: '/members/$slug'
      fullPath: '/members/$slug'
      preLoaderRoute: typeof MembersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tournaments': {
      id: '/admin/tournaments'
      path: '/tournaments'
      fullPath: '/admin/tournaments'
      preLoaderRoute: typeof AdminTournamentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/teams': {
      id: '/admin/teams'
      path: '/teams'
      fullPath: '/admin/teams'
      preLoaderRoute: typeof AdminTeamsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/participants': {
      id: '/admin/participants'
      path: '/participants'
      fullPath: '/admin/participants'
      preLoaderRoute: typeof AdminParticipantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/audit-log': {
      id: '/admin/audit-log'
      path: '/audit-log'
      fullPath: '/admin/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/tournaments/': {
      id: '/admin/tournaments/'
      path: '/'
      fullPath: '/admin/tournaments/'
      preLoaderRoute: typeof AdminTournamentsIndexRouteImport
      parentRoute: typeof AdminTournamentsRoute
    }
    '/admin/users/$memberId': {
      id: '/admin/users/$memberId'
      path: '/$memberId'
      fullPath: '/admin/users/$memberId'
      preLoaderRoute: typeof AdminUsersMemberIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/tournaments/$id': {
      id: '/admin/tournaments/$id'
      path: '/$id'
      fullPath: '/admin/tournaments/$id'
      preLoaderRoute: typeof AdminTournamentsIdRouteImport
      parentRoute: typeof AdminTournamentsRoute
    }
  }
}

interface AdminTournamentsRouteChildren {
  AdminTournamentsIdRoute: typeof AdminTournamentsIdRoute
  AdminTournamentsIndexRoute: typeof AdminTournamentsIndexRoute
}

const AdminTournamentsRouteChildren: AdminTournamentsRouteChildren = {
  AdminTournamentsIdRoute: AdminTournamentsIdRoute,
  AdminTournamentsIndexRoute: AdminTournamentsIndexRoute,
}

const AdminTournamentsRouteWithChildren =
  AdminTournamentsRoute._addFileChildren(AdminTournamentsRouteChildren)

interface AdminUsersRouteChildren {
  AdminUsersMemberIdRoute: typeof AdminUsersMemberIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersMemberIdRoute: AdminUsersMemberIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminParticipantsRoute: typeof AdminParticipantsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTeamsRoute: typeof AdminTeamsRoute
  AdminTournamentsRoute: typeof AdminTournamentsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminParticipantsRoute: AdminParticipantsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTeamsRoute: AdminTeamsRoute,
  AdminTournamentsRoute: AdminTournamentsRouteWithChildren,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface TeamsRouteChildren {
  TeamsIdRoute: typeof TeamsIdRoute
  TeamsCreateRoute: typeof TeamsCreateRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

const TeamsRouteChildren: TeamsRouteChildren = {
  TeamsIdRoute: TeamsIdRoute,
  TeamsCreateRoute: TeamsCreateRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}

const TeamsRouteWithChildren = TeamsRoute._addFileChildren(TeamsRouteChildren)

interface TournamentsRouteChildren {
  TournamentsIdRoute: typeof TournamentsIdRoute
  TournamentsIndexRoute: typeof TournamentsIndexRoute
}

const TournamentsRouteChildren: TournamentsRouteChildren = {
  TournamentsIdRoute: TournamentsIdRoute,
  TournamentsIndexRoute: TournamentsIndexRoute,
}

const TournamentsRouteWithChildren = TournamentsRoute._addFileChildren(
  TournamentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TeamsRoute: TeamsRouteWithChildren,
  TournamentsRoute: TournamentsRouteWithChildren,
  UnauthorizedRoute: UnauthorizedRoute,
  WaitlistRoute: WaitlistRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  MembersSlugRoute: MembersSlugRoute,
  ChampionsIndexRoute: ChampionsIndexRoute,
  CommunityIndexRoute: CommunityIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
